package com.ces2.guarderia_canina.enums;

public enum RazaPerro {
    LABRADOR,
    PASTOR_ALEMAN,
    GOLDEN_RETRIEVER,
    BULLDOG,
    CHIHUAHUA,
   	TERRYE,
    HUSKY,
	MALAMUTE,
    PIT_BULL,	
	BEAGLE, 
	BORDER_COLLIE,
	BOXER,
	BOYERO,
	CHOW_CHOW,
	COKER_SPANICH,
	DALMATA,
	DOGO, 
	FOX_TERRIER, 
	GALGO,
	GRAN_DANES,
	JAKC_RUSEELL,	
   YORKSHIRE_TERRIER,
	CRIOLLO, 
	NO_IDENTIFICADO
}